name: CI/CD Todo List

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Test Backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Test Backend
        run: |
          cd Backend
          pip install -r requirements.txt
          python manage.py test

      # Build Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './Frontend/package-lock.json'
      - name: Install and Build
        run: |
          cd Frontend
          npm install
          npm run build

      # Nouveau : Déploiement propre avec l'Action dédiée
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Frontend/dist # C'est ici que Vite génère les fichiers
